### ISSUE TITLE
Problem getting dot_tools

### ISSUE THREAD

**Issue by fairanswers** [timtadh/dot_tools#2]
I just switched centos VMs and my new one fails with
pip install dot_tools
Collecting dot_tools
  Could not find a version that satisfies the requirement dot_tools (from versions: )
No matching distribution found for dot_tools

I checked on pypi and didn't see dot_tools.
python -V
Python 2.7.5

uname -a
Linux bpm 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

What else can I look at?

Thx,
Joe

**Comment by fairanswers** [comment]
UPdated to use a 3.6 venv, and got the same result.   Also with easy_install

(venv) [jfair@bpm FairBPM]$ which easy_install
~/work/bpm/FairBPM/venv/bin/easy_install
(venv) [jfair@bpm FairBPM]$ easy_install dot_tools
Searching for dot_tools
Reading https://pypi.python.org/simple/dot_tools/
Reading https://pypi.python.org/simple/dot-tools/
Couldn't find index page for 'dot_tools' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for dot_tools
error: Could not find suitable distribution for Requirement.parse('dot_tools')

**Comment by fairanswers** [comment]
Apparently, that's what I did.

Sorry to bother you. I appreciate this tool! I'm making a workflow engine
to learn python, and keeping the state in dot files makes it easier to show
the progress.

Keep up the good work,
Joe

**Comment by timtadh** [comment]
Yep, dot is a great format to use and abuse. Let me know if you have any further issues.

**Comment by fairanswers** [comment]
Actually, I'm trying to write python like a real programmer, with tests and
everything, and I'm running into this problem when I run pytest

(venv) [jfair@bpm FairBPM]$ pytest
============================= test session starts
==============================
platform linux -- Python 3.4.8, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/jfair/work/bpm/FairBPM, inifile:
collected 0 items / 1 errors


==================================== ERRORS
====================================
______________________ ERROR collecting fair_bpm_test.py
_______________________
ImportError while importing test module
'/home/jfair/work/bpm/FairBPM/fair_bpm_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
fair_bpm_test.py:2: in <module>
    from fair_bpm import Say, Sing, FlexibleJobRunner, Process
fair_bpm.py:4: in <module>
    from dot_tools import parse, SimpleGraph
venv/lib64/python3.4/site-packages/dot_tools/__init__.py:8: in <module>
    import dot_parser, dot_lexer
E   ImportError: No module named 'dot_parser'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection
!!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.31 seconds
============================

Any ideas?

Thanks,
Joe
