### ISSUE TITLE
dot_tools not accessible after installation with setup.py

### ISSUE THREAD

**Issue by maximumspatium** [timtadh/dot_tools#3]
I'd like to try out dot_tools. Unfortunately, I'm not able to get it working.

I installed it with the following command:

`python setup.py install`

`pip list` shows that dot-tools 0.1 is installed.

When actually trying to import it as described in the README, I'm getting the following error:

```
Traceback (most recent call last):
  File "dotplay.py", line 1, in <module>
    from dot_tools import parser
ImportError: cannot import name 'parser'
```
Am I missing something?

BTW, Pip actually reports "dot-tools" instead of "dot_tools"...

Python version: 3.6.7
pip version: 18.1
setup tools version: 40.4.2
OS: macos 10.11.6

Thank you in advance!
Max

**Comment by timtadh** [comment]
Hi, I think the docs might be slightly incorrect. Try:

```
virtualenv --no-site-packages --python=$(which python2) env
source env/bin/activate
pip install -e git+https://github.com/timtadh/dot_tools#egg=dot_tools
python
>>> import dot_tools
>>> from dot_tools import parse
```

**Comment by maximumspatium** [comment]
Thanks for the quick help! I installed dot_tools as described in your post but it still doesn't work. I'm getting

```
>>> import dot_tools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maxim/src/dot-tools/dot_tools/__init__.py", line 8, in <module>
    import dot_parser, dot_lexer
ModuleNotFoundError: No module named 'dot_parser'
>>>
```

Virtualenv has been configured to use python27 from Macports...

**Comment by timtadh** [comment]
That is super weird. It sounds like an environment issue but it is hard for me to say what is going on remotely. I don't use a mac so I don't know what the interactions could be with Macports. Are other installations with pip working?

**Comment by maximumspatium** [comment]
Can the issue be caused by the underscore in the package name? According to [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names), the use of underscores in package names is discouraged because it can leads to subtle bugs.

> Are other installations with pip working?

Yes.

> I don't use a mac so I don't know what the interactions could be with Macports.

Well, I'll test it under Linux tonight to see if it works there...

**Comment by maximumspatium** [comment]
>  It sounds like an environment issue but it is hard for me to say what is going on remotely.

You were right. This was an issue with `virtualenv`. The solution is to install `virtualenv` using macports.

Sorry for the noise. I'll close this issue now.

**Comment by timtadh** [comment]
No problem. Glad you found the problem.
