### ISSUE TITLE
SyntaxError: LexToken(COLON,':',4,57)

### ISSUE THREAD

**Issue by maximumspatium** [timtadh/dot_tools#4]
I'm getting

`SyntaxError: LexToken(COLON,':',4,57)`

when processing [this DOT file](https://github.com/pfalcon/ScratchABlock/blob/master/tests/dom-idom.lst.exp.dot).

The issue is probably caused by the fact that the label attribute inside of [] is spread over two lines. Putting these attributes into a single line, i.e.

`"0" [label="0: BBlock(#9) idom: None"]`

solves the issue.

Graphviz' dot 2.40.1 does process the unmodified file just fine.

**Comment by timtadh** [comment]
Hi @maximumspatium looks like a bug in the lexer. I think you are right that the regex is wrong and should include the newline.

**Comment by timtadh** [comment]
should now be fixed in master.

**Comment by maximumspatium** [comment]
Thanks a lot!
